3400 #!/usr/bin/perl -w
3401 
3402 # Generate vectors.S, the trap/interrupt entry points.
3403 # There has to be one entry point per interrupt number
3404 # since otherwise there's no way for trap() to discover
3405 # the interrupt number.
3406 
3407 print "# generated by vectors.pl - do not edit\n";
3408 print "# handlers\n";
3409 print ".globl alltraps\n";
3410 for(my $i = 0; $i < 256; $i++){
3411     print ".globl vector$i\n";
3412     print "vector$i:\n";
3413     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
3414         print "  pushl \$0\n";
3415     }
3416     print "  pushl \$$i\n";
3417     print "  jmp alltraps\n";
3418 }
3419 
3420 print "\n# vector table\n";
3421 print ".data\n";
3422 print ".globl vectors\n";
3423 print "vectors:\n";
3424 for(my $i = 0; $i < 256; $i++){
3425     print "  .long vector$i\n";
3426 }
3427 
3428 # sample output:
3429 #   # handlers
3430 #   .globl alltraps
3431 #   .globl vector0
3432 #   vector0:
3433 #     pushl $0
3434 #     pushl $0
3435 #     jmp alltraps
3436 #   ...
3437 #
3438 #   # vector table
3439 #   .data
3440 #   .globl vectors
3441 #   vectors:
3442 #     .long vector0
3443 #     .long vector1
3444 #     .long vector2
3445 #   ...
3446 
3447 
3448 
3449 
